/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as CareWorkforceRouteImport } from './routes/care-workforce'
import { Route as PatientAssignmentRouteImport } from './routes/patient-assignment'
import { Route as PatientDashboardRouteImport } from './routes/patient-dashboard'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as WorkforceAssignmentRouteImport } from './routes/workforce-assignment'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const CareWorkforceRoute = CareWorkforceRouteImport.update({
  id: '/care-workforce',
  path: '/care-workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAssignmentRoute = PatientAssignmentRouteImport.update({
  id: '/patient-assignment',
  path: '/patient-assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/patient-dashboard',
  path: '/patient-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceAssignmentRoute = WorkforceAssignmentRouteImport.update({
  id: '/workforce-assignment',
  path: '/workforce-assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/care-workforce': typeof CareWorkforceRoute
  '/patient-assignment': typeof PatientAssignmentRoute
  '/patient-dashboard': typeof PatientDashboardRoute
  '/policies': typeof PoliciesRoute
  '/roster': typeof RosterRoute
  '/workforce-assignment': typeof WorkforceAssignmentRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/care-workforce': typeof CareWorkforceRoute
  '/patient-assignment': typeof PatientAssignmentRoute
  '/patient-dashboard': typeof PatientDashboardRoute
  '/policies': typeof PoliciesRoute
  '/roster': typeof RosterRoute
  '/workforce-assignment': typeof WorkforceAssignmentRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/care-workforce': typeof CareWorkforceRoute
  '/patient-assignment': typeof PatientAssignmentRoute
  '/patient-dashboard': typeof PatientDashboardRoute
  '/policies': typeof PoliciesRoute
  '/roster': typeof RosterRoute
  '/workforce-assignment': typeof WorkforceAssignmentRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/care-workforce'
    | '/patient-assignment'
    | '/patient-dashboard'
    | '/policies'
    | '/roster'
    | '/workforce-assignment'
    | '/tasks/$taskId'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/care-workforce'
    | '/patient-assignment'
    | '/patient-dashboard'
    | '/policies'
    | '/roster'
    | '/workforce-assignment'
    | '/tasks/$taskId'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/care-workforce'
    | '/patient-assignment'
    | '/patient-dashboard'
    | '/policies'
    | '/roster'
    | '/workforce-assignment'
    | '/tasks/$taskId'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  CareWorkforceRoute: typeof CareWorkforceRoute
  PatientAssignmentRoute: typeof PatientAssignmentRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
  PoliciesRoute: typeof PoliciesRoute
  RosterRoute: typeof RosterRoute
  WorkforceAssignmentRoute: typeof WorkforceAssignmentRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-workforce': {
      id: '/care-workforce'
      path: '/care-workforce'
      fullPath: '/care-workforce'
      preLoaderRoute: typeof CareWorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-assignment': {
      id: '/patient-assignment'
      path: '/patient-assignment'
      fullPath: '/patient-assignment'
      preLoaderRoute: typeof PatientAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-dashboard': {
      id: '/patient-dashboard'
      path: '/patient-dashboard'
      fullPath: '/patient-dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce-assignment': {
      id: '/workforce-assignment'
      path: '/workforce-assignment'
      fullPath: '/workforce-assignment'
      preLoaderRoute: typeof WorkforceAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  CareWorkforceRoute: CareWorkforceRoute,
  PatientAssignmentRoute: PatientAssignmentRoute,
  PatientDashboardRoute: PatientDashboardRoute,
  PoliciesRoute: PoliciesRoute,
  RosterRoute: RosterRoute,
  WorkforceAssignmentRoute: WorkforceAssignmentRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
