/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as CareWorkforceRouteImport } from './routes/care-workforce'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as StationsIndexRouteImport } from './routes/stations.index'
import { Route as StationsStationIdRouteImport } from './routes/stations.$stationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const CareWorkforceRoute = CareWorkforceRouteImport.update({
  id: '/care-workforce',
  path: '/care-workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsIndexRoute = StationsIndexRouteImport.update({
  id: '/stations/',
  path: '/stations/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsStationIdRoute = StationsStationIdRouteImport.update({
  id: '/stations/$stationId',
  path: '/stations/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/care-workforce': typeof CareWorkforceRoute
  '/patients': typeof PatientsRoute
  '/roster': typeof RosterRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/stations/': typeof StationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/care-workforce': typeof CareWorkforceRoute
  '/patients': typeof PatientsRoute
  '/roster': typeof RosterRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/stations': typeof StationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/care-workforce': typeof CareWorkforceRoute
  '/patients': typeof PatientsRoute
  '/roster': typeof RosterRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/stations/': typeof StationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/care-workforce'
    | '/patients'
    | '/roster'
    | '/stations/$stationId'
    | '/stations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/care-workforce'
    | '/patients'
    | '/roster'
    | '/stations/$stationId'
    | '/stations'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/care-workforce'
    | '/patients'
    | '/roster'
    | '/stations/$stationId'
    | '/stations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  CareWorkforceRoute: typeof CareWorkforceRoute
  PatientsRoute: typeof PatientsRoute
  RosterRoute: typeof RosterRoute
  StationsStationIdRoute: typeof StationsStationIdRoute
  StationsIndexRoute: typeof StationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-workforce': {
      id: '/care-workforce'
      path: '/care-workforce'
      fullPath: '/care-workforce'
      preLoaderRoute: typeof CareWorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/': {
      id: '/stations/'
      path: '/stations'
      fullPath: '/stations/'
      preLoaderRoute: typeof StationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/$stationId': {
      id: '/stations/$stationId'
      path: '/stations/$stationId'
      fullPath: '/stations/$stationId'
      preLoaderRoute: typeof StationsStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  CareWorkforceRoute: CareWorkforceRoute,
  PatientsRoute: PatientsRoute,
  RosterRoute: RosterRoute,
  StationsStationIdRoute: StationsStationIdRoute,
  StationsIndexRoute: StationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
